image: ruby:2.3

cache:
  paths:
  - vendor/

before_script:
  - gem install jekyll

pages:
  stage: deploy
  script:
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master