# Site settings
name: Proventa IT-Status
email: it-helpdesk@proventa.de
description: "Hier informieren wir über Störungen und Änderungen an der IT-Infrastruktur der Proventa AG. In unserem FAQ haben wir bereits einige häufige Proleme zusammen getragen. Sollte euer Problem dort nicht erklärt sein, wendet euch bitte an it-heldesk@proventa.de. Wir helfen euch gerne.<br><br>Eure IT Adminsi"
baseurl: ""
url: "https://it-status.proventa.de"
author: "IT Admins Proventa"

# Build settings
markdown: kramdown
permalink: pretty

include: [.htaccess, public_status.html]
timezone: Etc/UTC
