# Site settings
name: Proventa IT-Status
email: it-helpdesk@proventa.de
description: "IT-Status der Proventa AG"
baseurl: ""
url: "https://it-status.proventa.de"

# Build settings
markdown: kramdown
permalink: pretty
