# Site settings
name: Proventa IT-Status
email: it-helpdesk@proventa.de
description: "Hier informieren wir über Störungen und Änderungen an der IT-Infrastruktur der Proventa AG. Bei Fragen wendet euch bitte an it-heldesk@proventa.de."
baseurl: ""
url: "https://it-status.proventa.de"
author: "IT Admins Proventa"

# Build settings
markdown: kramdown
permalink: pretty

include: [.htaccess]
timezone: Etc/UTC
