#!/bin/bash
pushd ~/it-status >/dev/null
date=`date '+%F'`
mayday_files=$(find content/issues -name "${date}-*mayday*" | xargs grep -l 'resolved: false' )
if [ -n "${mayday_files}" ]; then

  git fetch >/dev/null 2>&1
  git reset --hard origin/master >/dev/null 2>&1

  for file in $mayday_files; do
   ./update_post "${file}" true <<EOF
Das Problem scheint behoben zu sein. Proventa Watchdog
EOF
  done
fi

popd >/dev/null
