#!/bin/bash
pushd ~/it-status >/dev/null
date=`date '+%F'`
mayday_files=$(find content/issues -name "${date}-*mayday*")
if [ -z "${mayday_files}" ]; then
git fetch >/dev/null 2>&1
git reset --hard origin/master >/dev/null 2>&1

./new_post "mayday mayday mayday" "Filoo,Untermainkai,HH1" "down" >/dev/null  2>&1 << EOF
{{/*update*/}}
Liebe KollegInnen,

Diese Nachricht wurde automatisch ausgelößt weil wir eine drastische Störung (z.B. Hardwareausfall) in der Infrastruktur haben.

Vor auslösen dieser Nachricht wurde die Interne IT per Mail und Telefon alarmiert und kümmert sich aktuell um die Behebung des Problems.

Die Kollegen informieren Sie, sobald es neuigkeiten gibt, an dieser Stelle.

**Bitte sehen Sie von Nachfragen zum Status ab.**

Viele liebe Grüße  
Proventa Watchdog
EOF
popd >/dev/null
fi
