#!/bin/bash
pushd ~/it-status >/dev/null
date=`date '+%F'`
mayday_files=$(find _posts -name "${date}-*mayday*")
if [ -z "${mayday_files}" ]; then
./new_post "mayday mayday mayday" >/dev/null  2>&1 << EOF
Liebe KollegInnen,

die ist eine automatisch erstelle Nachricht.

Sie wird ausgelößt wenn wir eine drastische Störung in der Infrastruktur haben.
Normalerweise bedeutet das einen Totalausfall wichtiger Komponenten.

Vor auslösen dieser Nachricht wurde die Interne IT per Mail und Telefon über den Ausfall informiert.
Die Kollegen kümmern sich aktuell um die Behebung des Problems.

Bitte sehen Sie von nachfragen zum Status ab.

Die Kollegen informieren Sie sobald wir das Problem eingegrenzt oder behoben haben an dieser Stelle.

Viele liebe Grüße
Proventa Watchdog
EOF
popd >/dev/null
fi
