#!/bin/sh
date=`date '+%F'`
time=`date '+%T'`
title="$1"
systems="$2"
if [ -z "$title" ]; then
  echo -n "Title:"
  read title
fi
if [ -z "$systems" ]; then
  echo -n "Affected systems (comma seperated):"
  read systems
fi

filetitle=$(echo $title | tr ' ' '-')
tempfile=$(mktemp)
file="content/issues/${date}-${filetitle}.markdown"
editor="nano"
if [ -n "$VISUAL" ]; then
    editor=$VISUAL
fi
affected=$(echo "$systems" | sed 's/,/\n  - /g')
cat >$file <<EOF
---
title:  "$title"
date:   $date $time
resolved: false
#resolvedWhen: $date $time
# Possible severity levels: down, disrupted, notice
severity: down
section: issue
affected:
  - $affected
---
EOF
if [ -t 0 ]; then
cp $file $tempfile
$editor +100 $file
if diff -q $file $tempfile >/dev/null; then
  echo "file not changed. aborting..."
  rm $file
  exit 1
fi
rm $tempfile
else
  cat >> $file
fi

git add .
git commit -m "new post: $title"
git push
