#!/bin/sh
date=`date '+%F'`
time=`date '+%T'`
title="$1"
if [ -z "$title" ]; then
  echo -n "Title:"
  read title
fi
filetitle=$(echo $title | tr ' ' '-')
tempfile=$(mktemp)
file="_posts/${date}-${filetitle}.markdown"
editor="nano"
if [ -n "$VISUAL" ]; then
    editor=$VISUAL
fi
cat >$file <<EOF
---
layout: post
title:  "$title"
date:   $date $time +0100
categories: active
---

EOF
if [ -t 0 ]; then
cp $file $tempfile
$editor +100 $file
if diff -q $file $tempfile >/dev/null; then
  echo "file not changed. aborting..."
  rm $file
  exit 1
fi
rm $tempfile
else 
  cat >> $file
fi

git add .
git commit -m "new post: $title"
git push

