#!/bin/sh
date=`date '+%F'`
time=`date '+%T'`
title="$1"
systems="$2"
severity="$3"
if [ -z "$title" ]; then
  echo "Title:"
  read title
fi
if [ -z "$systems" ]; then
  systems_options=$(grep '^affected:' --after-context=5 content/issues/*.md   | grep -- '-  - ' | cut -d ' ' -f 4 | sort -u | tr '\n' ',')
  echo "Affected systems (comma seperated; eg. ${systems_options}...):"
  read systems
fi
if [ -z "$severity" ]; then
  echo "Severirty (down, disrupted or notice)"
  read severity
fi


filetitle=$(echo $title | tr ' ' '-')
tempfile=$(mktemp)
file="content/issues/${date}-${filetitle}.md"
editor="nano"
if [ -n "$VISUAL" ]; then
    editor=$VISUAL
fi
affected=$(echo "$systems" | sed 's/,/\n  - /g')
cat >$file <<EOF
---
title:  "$title"
date:   $date $time
resolved: false
#resolvedWhen: $date $time
# Possible severity levels: down, disrupted, notice
severity: $severity
section: issue
affected:
  - $affected
---
EOF
if [ -t 0 ]; then
cp $file $tempfile
$editor +100 $file
if diff -q $file $tempfile >/dev/null; then
  echo "file not changed. aborting..."
  rm $file
  exit 1
fi
rm $tempfile
else
  cat >> $file
fi

git add .
git commit -m "new post: $title"
git push
